### PR TITLE
Clean up xrefs

### PR DESCRIPTION
**Pull request by cthoyt**
- Fix typos in PMID CURIEs
- Fix references to 2 patents
- Fix references to 2 books via ISSN

### CODE REVIEW

**Comment by cthoyt** [comment]
@chdudek you're listed as the contact for BTO on the OBO Foundry, can you please take a look at this?

CC @BRENDA-Enzymes

**Review by matentzn — APPROVED** [review]
These are good changes @BRENDA-Enzymes - please consider merging.

**Comment by cthoyt** [comment]
@chdudek would it also be possible to merge this?

**Comment by chdudek** [comment]
Thank you for your help @cthoyt !

**Pull request merged**
